apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sqlx-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sqlx-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sqlx-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if not .Values.argocd.hotReloadOnly }}
        checksum/config: {{ .Values.config | toYaml | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sqlx-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/sqlx-exporter/config.yaml
            - --log-level={{ .Values.logLevel }}
            {{- if .Values.watchRequired }}
            - --watch-required
            {{- end }}
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/sqlx-exporter
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          {{- include "sqlx-exporter.configVolume" . | nindent 10 }}
        - name: tmp
          emptyDir:
            medium: Memory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}