queries:
  oracle_active_sessions:
    # db не указан — возьмёт "azdh_oracle" из default_db этого файла
    sql: "SELECT count(1) FROM v$session WHERE status = 'ACTIVE' AND username IS NOT NULL"
    timeout: "10s"
    interval: "1m"

  oracle_db_is_up:
    # db не указан — возьмёт "azdh_oracle" из default_db этого файла
    sql: "SELECT 1 FROM dual"
    timeout: "5s"
    interval: "30s"

  oracle_blocking_sessions:
    # db не указан — возьмёт "azdh_oracle" из default_db этого файла
    sql: "SELECT count(1) FROM v$session WHERE blocking_session IS NOT NULL"
    timeout: "10s"
    interval: "2m"